server:
  address: 0.0.0.0  # 모든 IP에서 접근 가능하도록 설정
  port: 8080  # 원하는 포트 설정 가능

spring:
  application:
    name: bridge-code-be  # 프로젝트 이름 설정
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /management
