spring:
  application:
    name: community-project

  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL 8.x 버전
    hibernate:
      ddl-auto: update
    show-sql: true  # 실행되는 SQL 로그 출력
    properties:
      hibernate.format_sql: true  # SQL을 보기 좋게 정렬

server:
  port: 8080  # 기본 포트
